# Generated by Django 4.2.3 on 2023-08-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_alter_contact_options_and_more'),
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
    ]
